steps:
- id: 'buildConfirmation'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$PROJECT_ID"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "$SHORT_SHA"
      echo "$TAG_NAME"
      echo "$LOCATION"
      echo "$BUILD_ID"
      echo "***********************"

- name: gcr.io/k8s-skaffold/skaffold:v2.11.1
  id: skaffoldBuild
  args:
    - 'skaffold'
    - 'build'
    - '--profile=dev'
    - '--module=$_SKAFFOLD_MODULE'

options:
  # This allows for missing ENV variables.
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _ARTIFACT_REPO_NAME: cicd
  _SKAFFOLD_MODULE: client
