steps:
- id: 'buildConfirmation'
  name: 'alpine'
  entrypoint: 'sh'
  dir: /workspace
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$PROJECT_ID"
      echo "$REPO_NAME"
      echo "$BRANCH_NAME"
      echo "$SHORT_SHA"
      echo "$TAG_NAME"
      echo "$LOCATION"
      echo "$BUILD_ID"
      echo "***********************"

- id: 'cloudDeployDev'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: bash
  dir: /workspace
  args:
  - '-c'
  - |
      gcloud deploy releases create "$_SKAFFOLD_MODULE-$BUILD_ID"  \
        --delivery-pipeline="$_SKAFFOLD_MODULE" \
        --skaffold-file="src/skaffold.yaml" \
        --skaffold-version="2.11" \
        --region="$LOCATION"

options:
  # This allows for missing ENV variables.
  substitution_option: 'ALLOW_LOOSE'
substitutions:
  _DEPLOY_PIPELINE: client
