apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: frontend
profiles:
- name: dev
  build:
    googleCloudBuild: {}
    tagPolicy:
      gitCommit: {}
    artifacts:
    - image: apps/frontend
      context: .
  manifests:
    rawYaml:
      - ./run/*
  deploy:
    cloudrun:
      projectid: __PROJECT_ID__
      region: __LOCATION__
